ALTER TABLE inventory
    ADD COLUMN IF NOT EXISTS min_threshold INTEGER NOT NULL DEFAULT 10;

ALTER TABLE requests
    ADD COLUMN IF NOT EXISTS reviewed_by TEXT,
    ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS received_at TIMESTAMP;

ALTER TABLE loan
    ADD COLUMN IF NOT EXISTS source_warehouse TEXT;
